lib/tracker_api_web/router.ex
defmodule TrackerWeb.Router do
  use TrackerWeb, :router

  import TrackerWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TrackerWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :set_current_user do
    plug Tracker.Plugs.SetCurrentUser
  end

  pipeline :require_current_user do
    plug Tracker.Plugs.RequireCurrentUser
  end

  pipeline :require_admin_user do
    plug Tracker.Plugs.RequireAdminUser
  end

  scope "/", TrackerWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", TrackerWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: TrackerWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", TrackerWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", TrackerWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/admin", TrackerWeb do
    pipe_through [:browser, :require_authenticated_user, :require_admin_user]

    live "/", DashboardLive, :index
    live "/makes", MakeLive, :index
    live "/makes/new", MakeLive, :new
    live "/makes/:make_id", MakeDetailLive, :show
    live "/makes/:make_id/new", MakeDetailLive, :new
    live "/tracks", TrackLive, :index
    live "/tracks/new", TrackLive, :new
  end

  scope "/", TrackerWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end

  scope "/" do
    pipe_through [:api, :set_current_user]

    forward "/graphiql", Absinthe.Plug.GraphiQL, schema: TrackerWeb.Schema.Schema
  end

  scope "/" do
    pipe_through [:api, :set_current_user, :require_current_user]
    forward "/api", Absinthe.Plug, schema: TrackerWeb.Schema.Schema
  end

  scope "/", TrackerWeb do
    pipe_through [:api]

    post "/register", MobileUserSessionController, :register
    post "/login", MobileUserSessionController, :login
  end
end

lib/tracker_api_web/views/layout_view.ex
defmodule TrackerWeb.LayoutView do
  use TrackerWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/tracker_api_web/templates/layout/_user_menu.html.heex
<ul>
<%= if @current_user do %>
  <li><%= @current_user.email %></li>
  <li><%= link "Settings", to: Routes.user_settings_path(@conn, :edit) %></li>
  <li><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %></li>
<% else %>
  <%# <li><%= link "Register", to: Routes.user_registration_path(@conn, :new) %1></li> %>
  <li><%= link "Log in", to: Routes.user_session_path(@conn, :new) %></li>
<% end %>
</ul>

lib/tracker_api_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <header class="flex justify-between">
      <h1 class="font-bold text-xl">Tracker</h1>
      <%# <nav> %>
      <%#   <%= render "_user_menu.html", assigns %1> %>
      <%# </nav> %>
    </header>
  <%= @inner_content %>
</main>

lib/tracker_api_web/templates/layout/live.html.heex
<main>
  <header class="py-8 flex justify-between">
    <h1 class="text-xl font-bold text-secondary">Tracker</h1>
    <button phx-click={show_mobile_menu()}>
      <%= Heroicons.icon("bars-3", type: "outline", class: "h-8 w-8") %>
    </button>
  </header>
  <nav>
    <div id="mobile-nav-overlay" class="hidden items-center justify-center absolute inset-0 bg-white/20 z-20 opacity-0">
      <div id="mobile-nav" class="bg-bg-secondary p-4 rounded-md drop-shadow-md flex flex-col gap-y-2 w-2/3">
        <button phx-click={close_mobile_menu()} class="ml-auto mb-2">
          <%= Heroicons.icon("x-mark", type: "outline", class: "h-8 w-8") %>
        </button>
        <.link navigate={Routes.dashboard_path(@socket, :index)}>Dashboard</.link>  
        <.link navigate={Routes.make_path(@socket, :index)}>Motorcycles</.link>  
        <.link navigate={Routes.track_path(@socket, :index)}>Tracks</.link>  
      </div>
    </div>
  </nav>
  <p  role="alert"
      phx-click="lv:clear-flash"
      phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p  role="alert"
      phx-click="lv:clear-flash"
      phx-value-key="error"><%= live_flash(@flash, :error) %></p>
  <%= @inner_content %>
  <.live_component module={TrackerWeb.ModalComponent} id="modal" />
</main>

lib/tracker_api_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "Tracker", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body class="font-body text-primary bg-bg-primary mx-auto w-11/12 max-w-7xl">
    <%= @inner_content %>
  </body>
</html>